name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.lisp }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        lisp:
        - abcl
        - ccl
        - clasp
        - ecl
        - sbcl
        exclude:
        - os: ubuntu-latest
          lisp: ccl
        - os: macos-latest
          lisp: abcl
        - os: windows-latest
          lisp: abcl
        - os: windows-latest
          lisp: ccl
        - os: windows-latest
          lisp: clasp
        - os: windows-latest
          lisp: ecl

    # run the job on every combination of "os" above
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Ubuntu dependencies # we could only install what we need.
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y abcl ecl sbcl
        sudo bash -c "$(curl -fsSL https://www.thirdlaw.tech/pkg/clasp.sh)"
        echo "CONFIG_HOME=$HOME/.config" >> $GITHUB_ENV

    - name: Install MacOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install sbcl clozure-cl ecl clasp-developers/clasp/clasp-cl
        echo "CONFIG_HOME=$HOME/.config" >> $GITHUB_ENV

    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        choco install sbcl
        echo "CONFIG_HOME=$LOCALAPPDATA/config" >> $GITHUB_ENV

    - name: ABCL environment variables
      if: matrix.lisp == 'abcl'
      run: |
        echo -e "LISP=abcl\nLOAD=--load\nEVAL=--eval\nQUIT=--eval \"(quit)\"" >> $GITHUB_ENV

    - name: CCL environment variables
      if: matrix.lisp == 'ccl'
      run: |
        echo -e "LISP=ccl64\nLOAD=--load\nEVAL=--eval\nQUIT=--eval \"(quit)\"" >> $GITHUB_ENV

    - name: ECL environment variables
      if: matrix.lisp == 'ecl'
      run: |
        echo -e "LISP=ecl\nLOAD=--load\nEVAL=--eval\nQUIT=--eval \"(quit)\"" >> $GITHUB_ENV

    - name: CLASP environment variables
      if: matrix.lisp == 'clasp'
      run: |
        echo -e "LISP=clasp\nLOAD=--load\nEVAL=--eval\nQUIT=--quit" >> $GITHUB_ENV

    - name: SBCL environment variables
      if: matrix.lisp == 'sbcl'
      run: |
        echo -e "LISP=sbcl\nLOAD=--load\nEVAL=--eval\nQUIT=--quit" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: Install Quicklisp
      run: |
        mkdir -p $CONFIG_HOME/common-lisp/source-registry.conf.d
        echo "(:TREE #P\"${{ github.workspace }}/\")" > $CONFIG_HOME/common-lisp/source-registry.conf.d/00.conf
        curl -kLO https://beta.quicklisp.org/quicklisp.lisp
        $LISP $LOAD quicklisp.lisp $EVAL "(quicklisp-quickstart:install)" $EVAL "(ql-util:without-prompting (ql:add-to-init-file))" $QUIT
        $LISP $EVAL "(ql:quickload '(:clw))" $QUIT
        
    - name: Run Tests
      run: |
        $LISP $EVAL "(asdf:test-system :clw)"
